# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lr <- function(A, X, y, tau, l, sigma = 1, tol = 1e-4, max_iter = 1000L, verbose = 0L, scaled = 1L) {
    .Call('_SA24204148_lr', PACKAGE = 'SA24204148', A, X, y, tau, l, sigma, tol, max_iter, verbose, scaled)
}

lr_ <- function(A, X, y, tau, u, v, beta, u_distance, d, l, sigma, tol, max_iter, verbose, uv_is_init) {
    .Call('_SA24204148_lr_', PACKAGE = 'SA24204148', A, X, y, tau, u, v, beta, u_distance, d, l, sigma, tol, max_iter, verbose, uv_is_init)
}

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(N, thin) {
    .Call('_SA24204148_gibbsC', PACKAGE = 'SA24204148', N, thin)
}

#' @title Use three inputs to predict response using Rcpp.
#' @description The prediction model is described in http://www.babelgraph.org/wp/?p=358.
#' @param age the first predictor (numeric)
#' @param female the second predictor (logical)
#' @param ily the third predictor (logical)
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' data(data)
#' attach(data)
#' res <- vaccC(age,female,ily)
#' }
#' @export
vaccC <- function(age, female, ily) {
    .Call('_SA24204148_vaccC', PACKAGE = 'SA24204148', age, female, ily)
}

